# Superstore Project

## Import Libraries

In [2]:
# Import required libraries
import pandas as pd
import numpy as np

## Day 1: Data Exploration

In [3]:
# Load the dataset
data = pd.read_csv("Superstore_Messy.csv")

# Display first 5 rows
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
# Check rows, columns, column names, and data types
print("Rows and Columns:", data.shape)
print()

print("Column Names:")
print(data.columns.tolist())
print()

print("Data Types:")
print(data.dtypes)

Rows and Columns: (10044, 21)

Column Names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

Data Types:
Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code      float64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [5]:
# Basic information
print("Dataset Information:")
data.info()

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 10044 entries, 0 to 10043
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10044 non-null  int64
 1   Order ID       10044 non-null  str
 2   Order Date     10044 non-null  str
 3   Ship Date      10044 non-null  str
 4   Ship Mode      10044 non-null  str
 5   Customer ID    10044 non-null  str
 6   Customer Name  10004 non-null  str
 7   Segment        10044 non-null  str
 8   Country        10044 non-null  str
 9   City           10044 non-null  str
 10  State          10044 non-null  str
 11  Postal Code    10004 non-null  float64
 12  Region         10044 non-null  str
 13  Product ID     10044 non-null  str
 14  Category       10044 non-null  str
 15  Sub-Category   10044 non-null  str
 16  Product Name   10044 non-null  str
 17  Sales          10004 non-null  float64
 18  Quantity       10044 non-null  int64
 19  Discount       10044 non-null  float64
 20  Profit         10004 non-null  float64
dtypes: float64(4), int64(2), str(15)
memory usage: 1.6 MB

In [6]:
# Statistical summary of numerical columns
data.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,10044.000000,10004.000000,10004.000000,10044.000000,10044.000000,10004.000000
mean,4994.465253,55154.199320,255.108238,3.790422,0.156261,28.667871
std,2885.342882,32037.893863,1702.917481,2.224568,0.206516,233.940828
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2497.750000,23223.000000,17.332500,2.000000,0.000000,1.713750
50%,4989.500000,55901.000000,54.780000,3.000000,0.200000,8.636000
75%,7492.250000,90008.000000,209.970000,5.000000,0.200000,29.331600
max,9994.000000,99301.000000,121504.000000,14.000000,0.800000,8399.976000

In [7]:
# Unique values in important columns
important_cols = ["Category", "Sub-Category", "Segment", "Region"]

for col in important_cols:
    print(col, "unique values:")
    print(data[col].unique().tolist())
    print()

Category unique values:
['Furniture', 'Office Supplies', 'Technology', 'office supplies', 'technology', 'furniture']

Sub-Category unique values:
['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage', 'Furnishings', 'Art', 'Phones', 'Binders', 'Appliances', 'Paper', 'Accessories', 'Envelopes', 'Fasteners', 'Supplies', 'Machines', 'Copiers']

Segment unique values:
['Consumer', 'Corporate', 'Home Office']

Region unique values:
['South', 'West', 'Central', 'East']

In [8]:
# Day 1 Answers
rows, columns = data.shape
unique_categories = data["Category"].nunique()
most_frequent_region = data["Region"].value_counts().idxmax()
total_sales = data["Sales"].sum()
highest_sales_category = data.groupby("Category")["Sales"].sum().idxmax()

print("1. Rows and columns present in the dataset:", rows, "rows and", columns, "columns")
print("2. Number of unique categories:", unique_categories)
print("3. Region that appears most frequently:", most_frequent_region)
print("4. Total sales amount:", total_sales)
print("5. Category with highest sales:", highest_sales_category)

1. Rows and columns present in the dataset: 10044 rows and 21 columns
2. Number of unique categories: 6
3. Region that appears most frequently: West
4. Total sales amount: 2552102.8118999996
5. Category with highest sales: Technology

## Day 2: Data Quality Assessment

In [31]:
# 1. Check missing values
missing_values = data.isnull().sum()
print("Missing Values in Each Column:")
print(missing_values)

print("Rows that have missing values:\n",data[data.isnull().any(axis=1)].head())

Missing Values in Each Column:
Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name    40
Segment           0
Country           0
City              0
State             0
Postal Code      40
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales            40
Quantity          0
Discount          0
Profit           40
dtype: int64
Rows that have missing values:
      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
9        10  CA-2014-115812  06-09-2014   6/14/2014  Standard Class
203     204  US-2017-116701  12/17/2017  12/21/2017    Second Class
279     280  CA-2017-132976  10/13/2017  10/17/2017  Standard Class
289     290  CA-2016-110772  11/20/2016  11/24/2016    Second Class
301     302  CA-2016-142545  10/28/2016  11-03-2016  Standard Class

    Customer ID     Customer Name      Segment        Country          City  \
9      BH-11710   Brosina Hoffman     Consumer  United States   Los Angeles
203    LC-17140      Logan Currie     Consumer  United States        Dallas
279    AG-10495               NaN    Corporate  United States  Philadelphia
289    NZ-18565     Nick Zandusky  Home Office  United States      Columbus
301    JD-15895  Jonathan Doherty    Corporate  United States    Belleville

     ... Postal Code   Region       Product ID         Category Sub-Category  \
9    ...         NaN     West  OFF-AP-10002892  Office Supplies   Appliances
203  ...         NaN  Central  OFF-AP-10003217  Office Supplies   Appliances
279  ...     19140.0     East  OFF-LA-10002043  Office Supplies       Labels
289  ...     43229.0     East  OFF-FA-10002983  Office Supplies    Fasteners
301  ...      7109.0     East  FUR-FU-10001861        Furniture  Furnishings

                                          Product Name    Sales  Quantity  \
9                     Belkin F5C206VTEL 6 Outlet Surge  114.900         5
203               Eureka Sanitaire  Commercial Upright   66.284         2
279                                          Avery 489   24.840         3
289                     Advantus SlideClip Paper Clips   19.096         7
301  Floodlight Indoor Halogen Bulbs, 1 Bulb per Pa...      NaN         4

     Discount    Profit
9         0.0   34.4700
203       0.8 -178.9668
279       0.2    8.6940
289       0.2       NaN
301       0.0   38.0240

[5 rows x 21 columns]

In [10]:
# 2. Check duplicate records
duplicate_rows = data.duplicated().sum()

print("Duplicate rows:", duplicate_rows)
print("Answer: Duplicate rows should be removed because they can make analysis incorrect.")

Duplicate rows: 48
Answer: Duplicate rows should be removed because they can make analysis incorrect.

In [36]:
# 3. Inspect numerical columns
num_cols = data.select_dtypes(include="number").columns
print(num_cols)
print("Numerical Column Summary:")
print(data[num_cols].describe())
print()

print("Minimum Sales value:", data["Sales"].min())
print("Maximum Sales value:", data["Sales"].max())
print("Average Profit:", data["Profit"].mean())
print("Maximum Discount:", data["Discount"].max())

Index(['Row ID', 'Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit'], dtype='str')
Numerical Column Summary:
             Row ID   Postal Code          Sales      Quantity      Discount  \
count  10044.000000  10004.000000   10004.000000  10044.000000  10044.000000
mean    4994.465253  55154.199320     255.108238      3.790422      0.156261
std     2885.342882  32037.893863    1702.917481      2.224568      0.206516
min        1.000000   1040.000000       0.444000      1.000000      0.000000
25%     2497.750000  23223.000000      17.332500      2.000000      0.000000
50%     4989.500000  55901.000000      54.780000      3.000000      0.200000
75%     7492.250000  90008.000000     209.970000      5.000000      0.200000
max     9994.000000  99301.000000  121504.000000     14.000000      0.800000

             Profit
count  10004.000000
mean      28.667871
std      233.940828
min    -6599.978000
25%        1.713750
50%        8.636000
75%       29.331600
max     8399.976000

Minimum Sales value: 0.444
Maximum Sales value: 121504.0
Average Profit: 28.667870531787283
Maximum Discount: 0.8

In [ ]:
# 4. Inspect important categorical columns
cat_cols = ["Category", "Region", "Segment",'Sub-Category']

for col in cat_cols:
    print(col, "value counts:")
    print(data[col].value_counts())
    print()

category_most_records = data["Category"].value_counts().idxmax()
segment_most_frequent = data["Segment"].value_counts().idxmax()
region_fewest_records = data["Region"].value_counts().idxmin()

print("Category with most records:", category_most_records)
print("Segment appearing most frequently:", segment_most_frequent)
print("Region with fewest records:", region_fewest_records)

Category value counts:
Category
Office Supplies    5994
Furniture          2113
Technology         1837
office supplies      61
furniture            20
technology           19
Name: count, dtype: int64

Region value counts:
Region
West       3219
East       2860
Central    2335
South      1630
Name: count, dtype: int64

Segment value counts:
Segment
Consumer       5212
Corporate      3039
Home Office    1793
Name: count, dtype: int64

Sub-Category value counts:
Sub-Category
Binders        1530
Paper          1376
Furnishings     964
Phones          895
Storage         849
Art             802
Accessories     778
Chairs          621
Appliances      469
Labels          366
Tables          320
Envelopes       254
Bookcases       228
Fasteners       219
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

Country value counts:
Country
United States    10044
Name: count, dtype: int64

Category with most records: Office Supplies
Segment appearing most frequently: Consumer
Region with fewest records: South

In [47]:
# 5. Check date columns
print("Date Column Data Types:")
print(data[["Order Date", "Ship Date"]].dtypes)
print()

if (data["Order Date"].dtype == "string") or (data["Ship Date"].dtype == "string"):
    print("Answer: Dates are stored as text, so conversion to datetime is required later.")
else:
    print("Answer: Dates are already stored in datetime format.")

Date Column Data Types:
Order Date    str
Ship Date     str
dtype: object

Answer: Dates are stored as text, so conversion to datetime is required later.

In [48]:
# Data Quality Report
print("DATA QUALITY REPORT")
print("=" * 50)

print("1. Missing Values Summary")
print(missing_values[missing_values > 0])
print()

print("2. Duplicate Records Summary")
print("Duplicate rows found:", duplicate_rows)
print()

print("3. Numerical Column Observations")
print("Minimum Sales:", data["Sales"].min())
print("Maximum Sales:", data["Sales"].max())
print("Average Profit:", data["Profit"].mean())
print("Maximum Discount:", data["Discount"].max())
print()

print("4. Categorical Column Observations")
print("Category with most records:", category_most_records)
print("Segment appearing most frequently:", segment_most_frequent)
print("Region with fewest records:", region_fewest_records)
print()

print("5. Date Column Observations")
print("Order Date type:", data["Order Date"].dtype)
print("Ship Date type:", data["Ship Date"].dtype)
print()

print("6. Final Conclusion")
print("1. The dataset contains", rows, "rows and", columns, "columns.")
print("2. Missing values should be handled before analysis.")
print("3. Duplicate records should be removed.")
print("4. Date columns should be converted to datetime format.")
print("5. Numerical columns should be checked for unusual values or outliers.")

DATA QUALITY REPORT
==================================================
1. Missing Values Summary
Customer Name    40
Postal Code      40
Sales            40
Profit           40
dtype: int64

2. Duplicate Records Summary
Duplicate rows found: 48

3. Numerical Column Observations
Minimum Sales: 0.444
Maximum Sales: 121504.0
Average Profit: 28.667870531787283
Maximum Discount: 0.8

4. Categorical Column Observations
Category with most records: Office Supplies
Segment appearing most frequently: Consumer
Region with fewest records: South

5. Date Column Observations
Order Date type: str
Ship Date type: str

6. Final Conclusion
1. The dataset contains 10044 rows and 21 columns.
2. Missing values should be handled before analysis.
3. Duplicate records should be removed.
4. Date columns should be converted to datetime format.
5. Numerical columns should be checked for unusual values or outliers.

## Day 3: Data Cleaning

In [15]:
# Create a copy for cleaning
superstore_clean = data.copy()

# Store values before cleaning
missing_before = superstore_clean.isnull().sum()
duplicates_before = superstore_clean.duplicated().sum()
rows_before = superstore_clean.shape[0]

print("Rows before cleaning:", rows_before)
print("Missing values before cleaning:")
print(missing_before[missing_before > 0])
print("Duplicate rows before cleaning:", duplicates_before)

Rows before cleaning: 10044
Missing values before cleaning:
Customer Name    40
Postal Code      40
Sales            40
Profit           40
dtype: int64
Duplicate rows before cleaning: 48

In [74]:
# Detecting Outliers
numeric_cols=data.select_dtypes(include="number").drop(columns=["Sales","Quantity"]).columns
for column in numeric_cols:
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    
    outliers = data[(data[column] < lower_limit) | (data[column] > upper_limit)]
    
    print("Column:", column)
    print("Lower Limit:", lower_limit)
    print("Upper Limit:", upper_limit)
    print("Number of Outliers:", outliers.shape[0])
    print("Min value:",data[column].min())
    print("Max value:",data[column].max())

    print("-" * 40)

# we are dealing with quantity and sales separately because these values cannot be negative

cols=["Quantity","Sales"]
for column in cols:
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    lower_limit=max(0,lower_limit)
    outliers = data[(data[column] < lower_limit) | (data[column] > upper_limit)]
    
    print("Column:", column)
    print("Lower Limit:", lower_limit)
    print("Upper Limit:", upper_limit)
    print("Number of Outliers:", outliers.shape[0])
    print("Min value:",data[column].min())
    print("Max value:",data[column].max())

    print("-" * 40)

Column: Row ID
Lower Limit: -4994.0
Upper Limit: 14984.0
Number of Outliers: 0
Min value: 1
Max value: 9994
----------------------------------------
Column: Postal Code
Lower Limit: -76954.5
Upper Limit: 190185.5
Number of Outliers: 0
Min value: 1040.0
Max value: 99301.0
----------------------------------------
Column: Discount
Lower Limit: -0.30000000000000004
Upper Limit: 0.5
Number of Outliers: 861
Min value: 0.0
Max value: 0.8
----------------------------------------
Column: Profit
Lower Limit: -39.713024999999995
Upper Limit: 70.75837499999999
Number of Outliers: 1881
Min value: -6599.978
Max value: 8399.976
----------------------------------------
Column: Quantity
Lower Limit: 0
Upper Limit: 9.5
Number of Outliers: 171
Min value: 1
Max value: 14
----------------------------------------
Column: Sales
Lower Limit: 0
Upper Limit: 498.92625
Number of Outliers: 1171
Min value: 0.444
Max value: 121504.0
----------------------------------------

In [ ]:
#  Handle missing values

# Fill missing Customer Name with Unknown
superstore_clean["Customer Name"] = superstore_clean["Customer Name"].fillna("Unknown")

superstore_clean = superstore_clean.dropna(subset=["Postal Code"])

# Fill missing numerical values using median
for col in ["Sales", "Profit"]:

    superstore_clean[col] = superstore_clean[col].fillna(superstore_clean[col].median())

print("Missing values after treatment:")
print(superstore_clean.isnull().sum())

Missing values after treatment:
Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Country               0
City                  0
State                 0
Postal Code           0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Order Year            0
Order Month           0
Order Month Number    0
Delivery Days         0
Profit Margin         0
Profit Status         0
dtype: int64

In [50]:
# 2. Remove duplicate records
superstore_clean = superstore_clean.drop_duplicates()
rows_after_duplicates = superstore_clean.shape[0]

print("Duplicate rows found before cleaning:", duplicates_before)
print("Rows remaining after duplicate removal:", rows_after_duplicates)
print("Duplicate rows after cleaning:", superstore_clean.duplicated().sum())

Duplicate rows found before cleaning: 48
Rows remaining after duplicate removal: 9954
Duplicate rows after cleaning: 0

In [51]:
# 3. Check and correct data types
print("Data types before date conversion:")
print(superstore_clean[["Order Date", "Ship Date"]].dtypes)
print()

# Convert date columns into datetime
superstore_clean["Order Date"] = pd.to_datetime(superstore_clean["Order Date"], format="mixed")
superstore_clean["Ship Date"] = pd.to_datetime(superstore_clean["Ship Date"], format="mixed")


print("Data types after conversion:")
print(superstore_clean[["Order Date", "Ship Date"]].dtypes)

Data types before date conversion:
Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

Data types after conversion:
Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [ ]:
# 4. Clean text columns by removing extra spaces
text_cols = superstore_clean.select_dtypes(include=["object", "string"]).columns
for col in text_cols:
    superstore_clean[col] = superstore_clean[col].str.strip().str.title()
print("Text cleaning completed for these columns:")
print(list(text_cols))

Text cleaning completed for these columns:
['Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Order Month', 'Profit Status']

In [54]:
# 5. Verify the cleaned dataset
print("Cleaned Dataset Information:")
superstore_clean.info()
print()

print("Missing values after cleaning:")
print(superstore_clean.isnull().sum())
print()

print("Duplicate rows after cleaning:", superstore_clean.duplicated().sum())

Cleaned Dataset Information:
<class 'pandas.DataFrame'>
Index: 9954 entries, 0 to 9993
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row ID              9954 non-null   int64
 1   Order ID            9954 non-null   str
 2   Order Date          9954 non-null   datetime64[us]
 3   Ship Date           9954 non-null   datetime64[us]
 4   Ship Mode           9954 non-null   str
 5   Customer ID         9954 non-null   str
 6   Customer Name       9954 non-null   str
 7   Segment             9954 non-null   str
 8   Country             9954 non-null   str
 9   City                9954 non-null   str
 10  State               9954 non-null   str
 11  Postal Code         9954 non-null   float64
 12  Region              9954 non-null   str
 13  Product ID          9954 non-null   str
 14  Category            9954 non-null   str
 15  Sub-Category        9954 non-null   str
 16  Product Name        9954 non-null   str
 17  Sales               9954 non-null   float64
 18  Quantity            9954 non-null   int64
 19  Discount            9954 non-null   float64
 20  Profit              9954 non-null   float64
 21  Order Year          9954 non-null   int32
 22  Order Month         9954 non-null   str
 23  Order Month Number  9954 non-null   int32
 24  Delivery Days       9954 non-null   int64
 25  Profit Margin       9954 non-null   float64
 26  Profit Status       9954 non-null   str
dtypes: datetime64[us](2), float64(5), int32(2), int64(3), str(15)
memory usage: 2.1 MB

Missing values after cleaning:
Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Country               0
City                  0
State                 0
Postal Code           0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Order Year            0
Order Month           0
Order Month Number    0
Delivery Days         0
Profit Margin         0
Profit Status         0
dtype: int64

Duplicate rows after cleaning: 0

In [55]:
# Data Cleaning Report
rows_after_cleaning = superstore_clean.shape[0]

print("DATA CLEANING REPORT")
print("=" * 50)

print("1. Missing Value Treatment")
print("Missing columns before cleaning:")
print(missing_before[missing_before > 0])
print("Missing values were handled using fillna() and dropna().")
print()

print("2. Duplicate Removal Summary")
print("Duplicate rows found:", duplicates_before)
print("Rows before cleaning:", rows_before)
print("Rows after cleaning:", rows_after_cleaning)
print()

print("3. Data Type Corrections")
print("Order Date and Ship Date were converted to datetime.")
print("Postal Code was converted to integer after removing missing values.")
print()

print("4. Text Cleaning Summary")
print("Extra spaces were removed from text columns using str.strip().")
print()

print("5. Final Conclusion")
print("1. Missing values have been handled.")
print("2. Duplicate rows have been removed.")
print("3. Date columns are now in datetime format.")
print("4. Text columns are cleaned.")
print("5. The dataset is ready for feature engineering and analysis.")
print("6. The data loss cleaning.",(len(data)-len(superstore_clean))/len(data)*100)

DATA CLEANING REPORT
==================================================
1. Missing Value Treatment
Missing columns before cleaning:
Customer Name    40
Postal Code      40
Sales            40
Profit           40
dtype: int64
Missing values were handled using fillna() and dropna().

2. Duplicate Removal Summary
Duplicate rows found: 48
Rows before cleaning: 10044
Rows after cleaning: 9954

3. Data Type Corrections
Order Date and Ship Date were converted to datetime.
Postal Code was converted to integer after removing missing values.

4. Text Cleaning Summary
Extra spaces were removed from text columns using str.strip().

5. Final Conclusion
1. Missing values have been handled.
2. Duplicate rows have been removed.
3. Date columns are now in datetime format.
4. Text columns are cleaned.
5. The dataset is ready for feature engineering and analysis.
6. The data loss cleaning. 0.8960573476702508

## Day 4: Feature Engineering

In [22]:

# 2. Create Order Year
superstore_clean["Order Year"] = superstore_clean["Order Date"].dt.year

# 3. Create Order Month
superstore_clean["Order Month"] = superstore_clean["Order Date"].dt.month_name()
superstore_clean["Order Month Number"] = superstore_clean["Order Date"].dt.month

# 4. Create Delivery Days
superstore_clean["Delivery Days"] = (superstore_clean["Ship Date"] - superstore_clean["Order Date"]).dt.days

# 5. Create Profit Margin
superstore_clean["Profit Margin"] = (superstore_clean["Profit"] / superstore_clean["Sales"]) * 100

# 6. Create Profit Status
superstore_clean["Profit Status"] = np.where(superstore_clean["Profit"] > 0, "Profit", "Loss")

# Display first 5 rows with new columns
superstore_clean.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Order Year,Order Month,Order Month Number,Delivery Days,Profit Margin,Profit Status
0,1,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2016,November,11,3,16.00,Profit
1,2,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2016,November,11,3,30.00,Profit
2,3,Ca-2016-138688,2016-06-12,2016-06-16,Second Class,Dv-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2016,June,6,4,47.00,Profit
3,4,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2015,October,10,7,-40.00,Loss
4,5,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2015,October,10,7,11.25,Profit

In [56]:
# Day 4 Questions and Answers
most_orders_year = superstore_clean["Order Year"].value_counts().idxmax()
most_orders_month = superstore_clean["Order Month"].value_counts().idxmax()
avg_delivery_time = superstore_clean["Delivery Days"].mean()
avg_profit_margin = superstore_clean["Profit Margin"].mean()
loss_making_orders = superstore_clean[superstore_clean["Profit Status"] == "Loss"]

print("1. Year with most orders:", most_orders_year)
print("2. Month with most orders:", most_orders_month)
print("3. Average delivery time:", avg_delivery_time)
print("4. Number of loss-making orders:", loss_making_orders.shape[0])
print("5. Average profit margin:", avg_profit_margin)
print()

print("Loss-making orders sample:")
loss_making_orders[["Order ID", "Category", "Sub-Category", "Sales", "Profit", "Profit Status"]].head()

1. Year with most orders: 2017
2. Month with most orders: November
3. Average delivery time: 3.957604982921439
4. Number of loss-making orders: 1922
5. Average profit margin: 12.122258882747582

Loss-making orders sample:

,Order ID,Category,Sub-Category,Sales,Profit,Profit Status
3,Us-2015-108966,Furniture,Tables,957.5775,-383.0310,Loss
14,Us-2015-118983,Office Supplies,Appliances,68.8100,-123.8580,Loss
15,Us-2015-118983,Office Supplies,Binders,2.5440,-3.8160,Loss
23,Us-2017-156909,Furniture,Chairs,71.3720,-1.0196,Loss
27,Us-2015-150630,Furniture,Bookcases,3083.4300,-1665.0522,Loss

In [57]:
# Day 4 Observations
print("DAY 4 OBSERVATIONS")
print("=" * 50)
print("1. The year with the most orders is", most_orders_year)
print("2. The month with the most orders is", most_orders_month)
print("3. The average delivery time is", round(avg_delivery_time, 2), "days.")
print("4. There are", loss_making_orders.shape[0], "loss-making orders.")
print("5. The average profit margin is", round(avg_profit_margin, 2), "%.")

DAY 4 OBSERVATIONS
==================================================
1. The year with the most orders is 2017
2. The month with the most orders is November
3. The average delivery time is 3.96 days.
4. There are 1922 loss-making orders.
5. The average profit margin is 12.12 %.

## Group by Analysis Analysis

In [59]:
# Total sales by category
sales_by_category = superstore_clean.groupby("Category")["Sales"].sum().sort_values(ascending=False)
sales_by_category

Category
Technology         921516.9890
Furniture          872884.5089
Office Supplies    732970.2300
Name: Sales, dtype: float64

In [62]:
# Total profit by category
profit_by_category = superstore_clean.groupby("Category")["Profit"].sum().sort_values(ascending=False)
profit_by_category

Category
Technology         140863.6819
Office Supplies    122816.8196
Furniture           18179.4889
Name: Profit, dtype: float64

In [61]:
# Total sales by region
sales_by_region = superstore_clean.groupby("Region")["Sales"].sum().sort_values(ascending=False)
sales_by_region

Region
West       752987.6825
East       666026.8740
Central    596621.1304
South      511736.0410
Name: Sales, dtype: float64

In [60]:
# Monthly sales trend
monthly_sales = superstore_clean.groupby(["Order Year", "Order Month Number"])["Sales"].sum()
monthly_sales

Order Year  Order Month Number
2014        1                      14236.8950
            2                       4519.8920
            3                      57198.6410
            4                      28166.5130
            5                      23648.2870
            6                      34454.9676
            7                      33798.0790
            8                      27892.1285
            9                      81414.9708
            10                    129521.8010
            11                     78576.6527
            12                     69797.4105
2015        1                      18174.0756
            2                      11308.8290
            3                      37512.7076
            4                      33869.7465
            5                      30131.6865
            6                      28533.9660
            7                      28765.3250
            8                      37321.6922
            9                      63693.0920
            10                     31048.4935
            11                     89884.6435
            12                     74894.3812
2016        1                      18477.6270
            2                      22978.8150
            3                      51676.6090
            4                      38750.0390
            5                      56810.0040
            6                      40182.9660
            7                     157734.3270
            8                      31164.4963
            9                      89508.1089
            10                     59694.4330
            11                     79403.1458
            12                     96974.3390
2017        1                      44012.4880
            2                      20216.6874
            3                      58170.8468
            4                      36303.1841
            5                      44210.7582
            6                      52854.0097
            7                      45264.4160
            8                      63120.8880
            9                      85751.0940
            10                     66579.7492
            11                    116015.7910
            12                     83152.0288
Name: Sales, dtype: float64

In [63]:
# Final data quality check
print("Final Shape:", superstore_clean.shape)
print()
print("Missing Values:")
print(superstore_clean.isnull().sum())
print()
print("Duplicate Rows:", superstore_clean.duplicated().sum())

Final Shape: (9954, 27)

Missing Values:
Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Country               0
City                  0
State                 0
Postal Code           0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Order Year            0
Order Month           0
Order Month Number    0
Delivery Days         0
Profit Margin         0
Profit Status         0
dtype: int64

Duplicate Rows: 0

In [66]:
# Export final cleaned dataset
superstore_clean.to_csv("superstore_cleaned.csv", index=False)
print("Cleaned dataset saved as superstore_cleaned.csv")

Cleaned dataset saved as superstore_cleaned.csv